nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200']  # Allow Angular app
        allow_methods: ['GET', 'OPTIONS']        # Allowed HTTP methods
        allow_headers: ['Content-Type']          # Allowed headers
        max_age: 3600                            # Cache the preflight response
    paths:
        '^/products':  # Apply only to /products API route
            allow_origin: ['http://localhost:4200']
            allow_methods: ['GET', 'OPTIONS']
            allow_headers: ['Content-Type']